name: Binance Long + Short Scanner

on:
  schedule:
    - cron: "*/15 * * * *"
  workflow_dispatch:

jobs:
  scan:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.12"

      - name: Check files
        run: |
          pwd
          ls -la
          echo "Workflows:"
          ls -la .github/workflows || true

      - name: Run Binance Scanner
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python Bot.py
